In [313]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [314]:
#Step1: Read DataSet
data = pd.read_csv('../data/gia_nha.csv', index_col='ID_nha')
data.head()

        Dien_tich  So_phong  Gia_ty
ID_nha
1            5.65      4.98   3.278
2            6.14      3.08   3.271
3            1.26      3.32   1.066
4            2.54      3.94   1.825
5            7.17      3.17   3.387

In [315]:
#Step2: Extract data
features = ['Dien_tich', 'So_phong']
X = data[features]
y = data['Gia_ty']

In [316]:
#Step3: Split Train/Test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.8, test_size=0.2, random_state=42)

In [317]:
# Step 4: So sanh do phuc tap cua mo hinh

degrees = [1, 3, 5, 7, 9]

results = []

In [321]:
# Step 5: Train cac mo hinh voi cac degree khac nhau

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

for degree in degrees:

    # Tao polynomial features
    poly = PolynomialFeatures(
        degree=degree,
        include_bias=False
    )

    # Bien doi du lieu Train va Test
    X_train_poly = poly.fit_transform(X_train)
    X_test_poly = poly.transform(X_test)

    # Tao va train mo hinh
    model = LinearRegression()
    model.fit(X_train_poly, y_train)

    # Du doan
    y_train_pred = model.predict(X_train_poly)
    y_test_pred = model.predict(X_test_poly)

    # Tinh MSE
    train_mse = np.mean((y_train - y_train_pred) ** 2)
    test_mse = np.mean((y_test - y_test_pred) ** 2)

    
    results.append([
        degree,
        train_mse,
        test_mse
    ])

In [319]:
# Step 6: Ket qua

results_df = pd.DataFrame(
    results,
    columns=['Degree', 'Train MSE', 'Test MSE']
)

results_df

   Degree  Train MSE  Test MSE
0       1   0.009876  0.008485
1       3   0.005606  0.020915
2       5   0.003487  0.048748
3       7   0.001740  0.105716
4       9   0.016791  1.142368